FROM node:18 AS buildingstage  

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest

COPY ./nginxlocal/default.conf /etc/nginx/conf.d/default.conf

COPY --from=buildingstage /app/dist /usr/share/nginx/html
 
EXPOSE 80
EXPOSE 443
